//go:build ignore

package main

import (
	"fmt"
	"io"
	"os"
)

const (
	licPrefix = `//go:generate go run gen_license.go > license.go < ../../LICENSE
//
// NOTE: Code generated by go generate; DO NOT EDIT.

import (
	"os"
)

package main

func printLicense() {
	os.WriteString(license)
	os.Exit(0)
}

const license = `

	licPostfix = `
`
)

func main() {
	fmt.Print(licPrefix)
	fmt.Print("`")
	io.Copy(os.Stdout, os.Stdin)
	fmt.Print("`")
	fmt.Print(licPostfix)
}
